insert into public.glossary (zh, py, uz, ru, en, hsk) values
  ('吧', 'ba', '(-ylik) taklif yuklamasi', 'частица предложения', 'sentence particle', 1),
  ('白天', 'báitiān', 'kunduz', 'днём', 'in the afternoon', 1),
  ('不好意思', 'bù hǎoyìsi', 'uzr so''rayman', 'извините / простите', 'sorry / excuse me', 1),
  ('差', 'chà', 'yetishmaslik / qolmoq', 'не хватать / осталось', 'not enough / remaining', 1),
  ('迟到', 'chídào', 'kechikmoq', 'опоздать', 'to be late', 1),
  ('充电', 'chōngdiàn', 'zaryadka qilmoq', 'заряжать', 'to charge', 1),
  ('出发', 'chūfā', 'jo''namoq / yo''lga chiqmoq', 'отправиться / выехать', 'to set off / depart', 1),
  ('错', 'cuò', 'noto''g''ri / xato', 'неправильно / ошибка', 'wrong / mistake', 1),
  ('电梯', 'diàntī', 'lift', 'лифт', 'elevator / lift', 1),
  ('点菜', 'diǎn cài', 'ovqat buyurtma bermoq', 'заказать еду', 'to order food', 1),
  ('对', 'duì', 'ha, to''g''ri', 'да, верно', 'yes, correct', 1),
  ('对吗', 'duì ma', 'shundaymi?', 'правда?', 'really?', 1),
  ('多少钱', 'duōshao qián', 'qancha pul', 'сколько стоит', 'how much does it cost', 1),
  ('蛋糕', 'dàngāo', 'tort / pirojnoe', 'торт / пирожное', 'cake / pastry', 1),
  ('到', 'dào', 'yetib kelmoq', 'прибыть / приехать', 'to arrive', 1),
  ('等', 'děng', 'kutmoq', 'ждать', 'to wait', 1),
  ('打', 'dǎ', 'termoq / qo''ng''iroq qilmoq', 'набирать / звонить', 'to dial / call', 1),
  ('服务员', 'fúwùyuán', 'ofitsiant', 'официант', 'waiter', 1),
  ('发烧', 'fāshāo', 'isitma chiqmoq', 'температура / жар', 'temperature / fever', 1),
  ('飞机', 'fēijī', 'samolyot', 'самолёт', 'airplane', 1),
  ('封斋', 'fēng zhāi', 'ro''za tutmoq', 'соблюдать пост', 'to fast (observe fasting)', 1),
  ('分钟', 'fēnzhōng', 'daqiqa', 'минута', 'minute', 1),
  ('干嘛', 'gànma', 'nima qilyapsan', 'что делаешь / зачем', 'what are you doing / why', 1),
  ('刚才', 'gāngcái', 'hozirgina', 'только что', 'just now', 1),
  ('回来', 'huílái', 'qaytib kelmoq', 'вернуться', 'to come back / return', 1),
  ('火车', 'huǒchē', 'poyezd', 'поезд', 'train', 1),
  ('号码', 'hàomǎ', 'raqam / nomer', 'номер', 'number', 1),
  ('还', 'hái', 'hali / yana', 'ещё', 'still / more', 1),
  ('还是', 'háishi', 'yoki (tanlash savoli)', 'или (в вопросе выбора)', 'or (in choice questions)', 1),
  ('后面', 'hòumiàn', 'orqada / keyinda', 'сзади / позади', 'behind / in the back', 1),
  ('很高兴', 'hěn gāoxìng', 'juda xursand', 'очень рад(а)', 'very glad / pleased', 1),
  ('叫', 'jiào', 'deb atalmoq / ismim ... bo''lmoq', 'звать / называться', 'to be called / named', 1),
  ('加班', 'jiābān', 'qo''shimcha ishlamoq', 'работать сверхурочно', 'to work overtime', 1),
  ('接电话', 'jiē diànhuà', 'telefonga javob bermoq', 'ответить на звонок', 'to answer a call', 1),
  ('减肥', 'jiǎnféi', 'ozmoq / vazn tashlamoq', 'худеть / сбрасывать вес', 'to lose weight', 1),
  ('久', 'jiǔ', 'uzoq (vaqt)', 'долго', 'long (time)', 1),
  ('系', 'jì', 'taqmoq / bog''lamoq', 'пристегнуть / завязать', 'to fasten / buckle', 1),
  ('斤', 'jīn', 'jin (0,5 kg)', 'цзинь (0,5 кг)', 'jin (0.5 kg)', 1),
  ('今天', 'jīntiān', 'bugun', 'сегодня', 'today', 1),
  ('几点', 'jǐ diǎn', 'soat necha', 'который час / во сколько', 'what time / at what time', 1),
  ('紧张', 'jǐnzhāng', 'hayajonlanmoq', 'нервничать', 'to be nervous', 1),
  ('快', 'kuài', 'tez / tezroq', 'быстро / быстрее', 'fast / faster', 1),
  ('开会', 'kāihuì', 'yig''ilish o''tkazmoq', 'проводить совещание', 'to hold a meeting', 1),
  ('开始', 'kāishǐ', 'boshlamoq', 'начинать / начать', 'to begin / start', 1),
  ('可以', 'kěyǐ', 'mumkin, bo''ladi', 'можно, разрешается', 'may / is allowed', 1),
  ('考试', 'kǎoshì', 'imtihon', 'экзамен', 'exam', 1),
  ('辣', 'là', 'achchiq', 'острый', 'spicy', 1),
  ('来', 'lái', 'olib keling (buyurtma)', 'дайте, принесите (при заказе)', 'give / bring (when ordering)', 1),
  ('楼下', 'lóuxià', 'bino pastida', 'внизу (у дома)', 'downstairs (at the entrance)', 1),
  ('面条', 'miàntiáo', 'lag''mon / noodle', 'лапша', 'noodles', 1),
  ('忙', 'máng', 'band', 'занят', 'busy', 1),
  ('没关系', 'méi guānxi', 'hech gap emas', 'ничего страшного', 'no problem / it''s okay', 1),
  ('门口', 'ménkǒu', 'eshik oldi / kirish joyi', 'у входа / у двери', 'at the entrance / at the door', 1),
  ('明天', 'míngtiān', 'ertaga', 'завтра', 'tomorrow', 1),
  ('名字', 'míngzi', 'ism', 'имя', 'name', 1),
  ('买单', 'mǎidān', 'hisob so''ramoq', 'попросить счёт', 'to ask for the bill', 1),
  ('米饭', 'mǐfàn', 'guruch', 'рис', 'rice', 1),
  ('拿', 'ná', 'olmoq, ko''tarmoq', 'взять, нести', 'to take / carry', 1),
  ('能', 'néng', '-a olmoq (qobiliyat)', 'мочь (способность)', 'can (ability)', 1),
  ('哪儿', 'nǎr', 'qayerda', 'где', 'where', 1),
  ('你好', 'nǐ hǎo', 'salom', 'привет / здравствуйте', 'hello', 1),
  ('请问', 'qǐngwèn', 'kechirasiz / aytingchi', 'скажите пожалуйста', 'excuse me, please', 1),
  ('认识', 'rènshi', 'tanishmoq', 'познакомиться / знать', 'to get to know / to know', 1),
  ('刷卡', 'shuākǎ', 'karta bilan to''lamoq', 'оплатить картой', 'to pay by card', 1),
  ('说一声', 'shuō yì shēng', 'bir og''iz aytmoq', 'предупредить / сказать', 'to inform / tell', 1),
  ('什么', 'shénme', 'nima', 'что / какой', 'what / which', 1),
  ('事情', 'shìqing', 'ish / narsa', 'дело / вещь', 'matter / thing', 1),
  ('手里', 'shǒu lǐ', 'qo''lda', 'в руке', 'in hand', 1),
  ('送', 'sòng', 'kuzatmoq / olib bormoq', 'проводить / отвезти', 'to see off / give a ride', 1),
  ('头疼', 'tóuténg', 'bosh og''rig''i', 'головная боль', 'headache', 1),
  ('外卖', 'wàimài', 'dostavka taomi', 'доставка еды', 'food delivery', 1),
  ('完', 'wán', 'tugatmoq / bitmoq', 'закончить / завершить', 'to finish / complete', 1),
  ('喂', 'wèi', 'alo', 'алло', 'hello (on the phone)', 1),
  ('为什么', 'wèi shénme', 'nega, nima uchun', 'почему, зачем', 'why', 1),
  ('晚上', 'wǎnshang', 'kechqurun', 'вечером', 'in the evening', 1),
  ('下次', 'xià cì', 'keyingi safar', 'в следующий раз', 'next time', 1),
  ('下个月', 'xià ge yuè', 'keyingi oy', 'в следующем месяце', 'next month', 1),
  ('下班', 'xiàbān', 'ishdan chiqmoq', 'закончить работу', 'to finish work', 1),
  ('下去', 'xiàqù', 'pastga tushmoq', 'спуститься', 'to go down', 1),
  ('写', 'xiě', 'yozmoq', 'писать', 'to write', 1),
  ('休息', 'xiūxi', 'dam olmoq', 'отдыхать', 'to rest', 1),
  ('学校', 'xuéxiào', 'maktab', 'школа', 'school', 1),
  ('辛苦', 'xīnkǔ', 'qiyin, mashaqqatli', 'трудно, тяжело', 'difficult / hard', 1),
  ('要', 'yào', '(-moqchi) / tez orada', 'собираться / скоро', 'to be about to / soon', 1),
  ('一份', 'yí fèn', 'bir porsiya', 'одна порция', 'one serving', 1),
  ('一半', 'yíbàn', 'yarmi', 'половина', 'half', 1),
  ('一共', 'yígòng', 'hammasi bo''lib', 'всего, итого', 'in total', 1),
  ('一下', 'yíxià', 'biroz / bir lahza', 'немного / разок', 'a little / just once', 1),
  ('也', 'yě', 'ham', 'тоже', 'also / too', 1),
  ('因为', 'yīnwèi', 'chunki', 'потому что', 'because', 1),
  ('有点', 'yǒudiǎn', 'biroz', 'немного', 'a little', 1),
  ('这么', 'zhème', 'shuncha / buncha', 'так / настолько', 'so / so much', 1),
  ('斋月', 'zhāi yuè', 'Ramazon oyi', 'месяц Рамадан', 'month of Ramadan', 1),
  ('准备', 'zhǔnbèi', 'tayyorlanmoq', 'готовиться', 'to prepare', 1),
  ('最近', 'zuìjìn', 'yaqinda / oxirgi paytlarda', 'в последнее время / недавно', 'recently / lately', 1),
  ('坐', 'zuò', 'minmoq (transport)', 'ехать на (транспорте)', 'to go by (transport)', 1),
  ('作业', 'zuòyè', 'uy vazifasi', 'домашнее задание', 'homework', 1),
  ('在', 'zài', '-da / joylashgan', 'в / на / находиться', 'at / in / to be at', 1),
  ('再', 'zài', 'yana, qayta', 'ещё, снова', 'again / once more', 1),
  ('早点', 'zǎo diǎn', 'ertaroq / tezroq', 'пораньше', 'earlier', 1),
  ('走', 'zǒu', 'ketmoq / yurmoq', 'уходить / идти', 'to leave / go', 1),
  ('安全带', 'ānquándài', 'xavfsizlik kamari', 'ремень безопасности', 'seatbelt', 1),
  ('A 离 B 多远', 'A lí B duō yuǎn', 'A B dan qancha uzoq', 'Как далеко А от Б', 'How far is A from B', 2),
  ('别着急', 'bié zháojí', 'xavotir olma', 'не волнуйся', 'don''t worry', 2),
  ('别人', 'biéren', 'boshqalar, o''zga odamlar', 'другие (люди)', 'others, other people', 2),
  ('帮助', 'bāngzhù', 'yordam bermoq; yordam', 'помогать; помощь', 'to help; help', 2),
  ('杯子', 'bēizi', 'stakan', 'чашка', 'cup', 2),
  ('带', 'dài', 'olib kelmoq, olib yurmoq', 'брать с собой, носить', 'to bring, to carry', 2),
  ('都', 'dōu', 'hammasi, har doim', 'все, всё', 'all, every (emphatic)', 2),
  ('打电话', 'dǎ diànhuà', 'qo''ng''iroq qilmoq', 'звонить', 'to make a phone call', 2),
  ('放好', 'fàng hǎo', 'joyiga qo''ymoq', 'убрать на место', 'to put away properly', 2),
  ('房间', 'fángjiān', 'xona', 'комната, номер', 'room', 2),
  ('贵', 'guì', 'qimmat', 'дорогой', 'expensive', 2),
  ('干净', 'gānjìng', 'toza', 'чистый', 'clean', 2),
  ('公园', 'gōngyuán', 'park, bog''', 'парк', 'park', 2),
  ('工作', 'gōngzuò', 'ish; ishlamoq', 'работа; работать', 'job; to work', 2),
  ('火车站', 'huǒchēzhàn', 'vokzal, temir yo''l bekati', 'вокзал', 'train station', 2),
  ('后口袋', 'hòu kǒudài', 'orqa cho''ntak', 'задний карман', 'back pocket', 2),
  ('喝', 'hē', 'ichmoq', 'пить', 'to drink', 2),
  ('好看', 'hǎokàn', 'chiroyli', 'красивый', 'good-looking, nice', 2),
  ('教', 'jiāo', 'o''qitmoq, dars bermoq', 'преподавать, учить', 'to teach', 2),
  ('觉得', 'juéde', 'deb hisoblamoq, o''ylamoq', 'думать, считать', 'to feel, to think', 2),
  ('鸡肉', 'jīròu', 'tovuq go''shti', 'курица (мясо)', 'chicken (meat)', 2),
  ('几次', 'jǐ cì', 'necha marta', 'сколько раз', 'how many times', 2),
  ('咖啡店', 'kāfēidiàn', 'qahvaxona', 'кофейня', 'coffee shop', 2),
  ('可是', 'kěshì', 'lekin, ammo', 'но, однако', 'but, however', 2),
  ('蓝色', 'lánsè', 'ko''k (rang)', 'синий', 'blue', 2),
  ('冷', 'lěng', 'sovuq', 'холодный', 'cold', 2),
  ('每隔一天', 'měi gé yì tiān', 'kun ora', 'через день', 'every other day', 2),
  ('每天', 'měitiān', 'har kuni', 'каждый день', 'every day', 2),
  ('买', 'mǎi', 'sotib olmoq', 'покупать', 'to buy', 2),
  ('难', 'nán', 'qiyin', 'трудный', 'difficult, hard', 2),
  ('便宜', 'piányi', 'arzon', 'дешёвый', 'cheap', 2),
  ('跑步', 'pǎobù', 'yugurmoq', 'бегать, бег', 'to run, running', 2),
  ('前面', 'qiánmiàn', 'oldinda', 'впереди, спереди', 'in front, ahead', 2),
  ('上课', 'shàng kè', 'darsda bo''lmoq', 'на уроке', 'to be in class', 2),
  ('试一试', 'shì yi shì', 'kiyib ko''rmoq', 'примерить, попробовать', 'to try (on)', 2),
  ('试衣间', 'shìyījiān', 'kiyinish xonasi', 'примерочная', 'fitting room', 2),
  ('时候', 'shíhou', 'payt, vaqt', 'во время, в течение', '(the time) when, during', 2),
  ('书包', 'shūbāo', 'maktab sumkasi', 'школьный портфель', 'schoolbag', 2),
  ('少', 'shǎo', 'kam, oz', 'мало', 'few, little', 2),
  ('手机', 'shǒujī', 'mobil telefon', 'мобильный телефон', 'cell phone', 2),
  ('天气', 'tiānqì', 'ob-havo', 'погода', 'weather', 2),
  ('听', 'tīng', 'tinglamoq', 'слушать', 'to listen', 2),
  ('下雨', 'xià yǔ', 'yomg''ir yog''moq', 'идёт дождь', 'to rain', 2),
  ('响', 'xiǎng', 'jiringlamoq', 'звенеть', 'to ring', 2),
  ('学习', 'xuéxí', 'o''rganmoq', 'учить, заниматься', 'to study', 2),
  ('星期', 'xīngqī', 'hafta', 'неделя', 'week', 2),
  ('喜欢', 'xǐhuan', 'yoqtirmoq', 'нравиться, любить', 'to like', 2),
  ('颜色', 'yánsè', 'rang', 'цвет', 'color', 2),
  ('一杯茶', 'yì bēi chá', 'bir piyola choy', 'чашка чая', 'a cup of tea', 2),
  ('一杯水', 'yì bēi shuǐ', 'bir stakan suv', 'стакан воды', 'a glass of water', 2),
  ('一碗面条', 'yì wǎn miàntiáo', 'bir kosa ugra', 'миска лапши', 'a bowl of noodles', 2),
  ('一件', 'yí jiàn', 'bitta (kiyim)', 'одна (вещь одежды)', 'one (item of clothing)', 2),
  ('运动', 'yùndòng', 'sport, mashq qilmoq', 'спорт, заниматься спортом', 'to exercise, sports', 2),
  ('衣服', 'yīfu', 'kiyim', 'одежда', 'clothes', 2),
  ('医生', 'yīshēng', 'shifokor, doktor', 'врач', 'doctor', 2),
  ('医院', 'yīyuàn', 'kasalxona', 'больница', 'hospital', 2),
  ('以后', 'yǐhòu', 'kelajakda, keyin', 'в будущем, потом', 'in the future, later', 2),
  ('有一点', 'yǒu yìdiǎn', 'ozgina, biroz', 'немного', 'a little, a bit', 2),
  ('有意思', 'yǒu yìsi', 'qiziqarli', 'интересный', 'interesting', 2),
  ('桌子', 'zhuōzi', 'stol', 'стол', 'table', 2),
  ('住', 'zhù', 'yashamoq, qolmoq (tunash)', 'жить, останавливаться', 'to stay, to live', 2),
  ('中文', 'Zhōngwén', 'Xitoy tili', 'китайский язык', 'Chinese (language)', 2),
  ('找', 'zhǎo', 'qidirmoq', 'искать', 'to look for', 2),
  ('只', 'zhǐ', 'faqat', 'только', 'only', 2),
  ('坐车', 'zuò chē', 'mashinada', 'на машине', 'by car', 2),
  ('昨天', 'zuótiān', 'kecha', 'вчера', 'yesterday', 2),
  ('左边', 'zuǒbiān', 'chap tomon', 'левая сторона, слева', 'left side', 2),
  ('怎么办', 'zěnme bàn', 'nima qilaman?', 'что делать?', 'what to do?', 2),
  ('怎么样', 'zěnmeyàng', 'qanday? qalay?', 'как? каков?', 'how about? how is it?', 2),
  ('走路', 'zǒulù', 'piyoda yurmoq', 'ходить пешком', 'to walk', 2),
  ('饿', 'è', 'och', 'голодный', 'hungry', 2),
  ('安静', 'ānjìng', 'tinch, jim', 'тихий, спокойный', 'quiet', 2),
  ('搬家', 'bānjiā', 'ko''chmoq (uy almashtirmoq)', 'переезжать', 'to move house', 3),
  ('吵', 'chǎo', 'shovqinli', 'шумный', 'noisy', 3),
  ('大概', 'dàgài', 'taxminan', 'примерно, приблизительно', 'approximately, about', 3),
  ('打扫', 'dǎsǎo', 'tozalamoq, supurmoq', 'убирать, подметать', 'to clean, to sweep', 3),
  ('方便', 'fāngbiàn', 'qulay', 'удобный', 'convenient', 3),
  ('经常', 'jīngcháng', 'tez-tez, ko''pincha', 'часто', 'often', 3),
  ('骑自行车', 'qí zìxíngchē', 'velosipedda yurmoq', 'ездить на велосипеде', 'to ride a bike', 3),
  ('睡不着', 'shuì bu zháo', 'uxlay olmaslik', 'не мочь уснуть', 'to be unable to fall asleep', 3),
  ('算', 'suàn', 'hisoblanmoq, deb sanalmoq', 'считаться', 'to count as, to be considered', 3),
  ('虽然', 'suīrán', 'garchi, ...sa-da', 'хотя', 'although', 3),
  ('已经', 'yǐjīng', 'allaqachon', 'уже', 'already', 3),
  ('周末', 'zhōumò', 'dam olish kuni, hafta oxiri', 'выходные', 'weekend', 3),
  ('重复', 'chóngfù', 'takrorlanadigan, takrorlamoq', 'повторять, повторяющийся', 'to repeat; repetitive', 5),
  ('处理', 'chǔlǐ', 'hal qilmoq, ko''rib chiqmoq, bajarmoq', 'решать, обрабатывать, справляться', 'to handle; to deal with', 5),
  ('发展', 'fāzhǎn', 'rivojlanish, taraqqiyot', 'развитие, рост', 'development; growth', 5),
  ('发展空间', 'fāzhǎn kōngjiān', 'rivojlanish imkoni, o''sish imkoniyati', 'пространство для роста, перспективы развития', 'room for growth; development potential', 5),
  ('工资', 'gōngzī', 'maosh, ish haqi', 'зарплата', 'salary; wages', 5),
  ('沟通', 'gōutōng', 'muloqot qilmoq, gaplashib kelishmoq', 'общаться, налаживать контакт', 'to communicate', 5),
  ('改变', 'gǎibiàn', 'o''zgartirmoq, o''zgarish', 'изменять, изменение', 'to change; change', 5),
  ('环境', 'huánjìng', 'muhit, atrof-muhit, sharoit', 'обстановка, среда', 'environment', 5),
  ('合作', 'hézuò', 'hamkorlik qilmoq, hamkorlik', 'сотрудничать, сотрудничество', 'to cooperate; cooperation', 5),
  ('建议', 'jiànyì', 'maslahat, taklif; maslahat bermoq', 'совет, предложение; советовать', 'suggestion; advice; to suggest', 5),
  ('接触', 'jiēchù', 'duch kelmoq, tanishmoq, ish olib bormoq', 'соприкасаться, иметь дело с, знакомиться', 'to come into contact with; to get exposure to', 5),
  ('决定', 'juédìng', 'qaror qilmoq, qaror', 'решать, решение', 'to decide; decision', 5),
  ('机会', 'jīhuì', 'imkoniyat, fursat', 'возможность, шанс', 'opportunity; chance', 5),
  ('空间', 'kōngjiān', 'bo''shliq, joy, makon', 'пространство, место', 'space; room', 5),
  ('考虑', 'kǎolǜ', 'o''ylab ko''rmoq, mulohaza qilmoq', 'обдумывать, рассматривать', 'to consider; to think about', 5),
  ('领导', 'lǐngdǎo', 'rahbar, boshliq', 'руководитель, начальник', 'leader; boss; manager', 5),
  ('内容', 'nèiróng', 'mazmun, mundarija', 'содержание', 'content; work content', 5),
  ('确实', 'quèshí', 'haqiqatan ham, rostdan ham', 'действительно, в самом деле', 'indeed; really', 5),
  ('任务', 'rènwu', 'vazifa, topshiriq', 'задача, задание', 'task; assignment', 5),
  ('适合', 'shìhé', 'mos kelmoq, to''g''ri kelmoq', 'подходить, годиться', 'to suit; to be suitable for', 5),
  ('升职', 'shēngzhí', 'lavozimi ko''tarilmoq, mansabga ko''tarilmoq', 'получить повышение', 'to get promoted', 5),
  ('条件', 'tiáojiàn', 'shart, sharoit, taklif', 'условия', 'conditions; terms; offer', 5),
  ('挑战', 'tiǎozhàn', 'sinov, qiyinchilik, chaqiriq', 'вызов, испытание', 'challenge', 5),
  ('团队', 'tuánduì', 'jamoa, guruh', 'команда', 'team', 5),
  ('同事', 'tóngshì', 'hamkasb, ish o''rtog''i', 'коллега, сослуживец', 'colleague; coworker', 5),
  ('稳妥', 'wěntuǒ', 'ishonchli, ehtiyotkor, oqilona', 'надёжный, разумный, осмотрительный', 'safe; reliable; prudent; sensible', 5),
  ('项目', 'xiàngmù', 'loyiha', 'проект', 'project', 5),
  ('心事', 'xīnshì', 'tashvish, ko''ngildagi dard', 'переживание, забота; то, что на душе', 'worry; something on one''s mind', 5),
  ('一方面……另一方面……', 'yì fāngmiàn… lìng yì fāngmiàn…', 'bir tomondan… ikkinchi tomondan…', 'с одной стороны… с другой стороны…', 'on one hand… on the other hand…', 5),
  ('犹豫', 'yóuyù', 'ikkilanmoq, taraddudlanmoq', 'колебаться, сомневаться', 'to hesitate', 5),
  ('压力', 'yālì', 'bosim, ruhiy bosim, stress', 'давление, стресс', 'pressure; stress', 5),
  ('状态', 'zhuàngtài', 'holat, ahvol, kayfiyat', 'состояние', 'state; condition', 5)
on conflict (zh, py_norm) do nothing;

-- Canonical resolutions for the conflicting words (human decisions, Phase 2).
-- Applied AFTER glossary-seed.sql. The auto seed used first-occurrence values;
-- these set the agreed canonical gloss. py/hsk are unchanged (only translations).
update public.glossary set uz='ham',                        ru='тоже, также',          en='also, too'            where zh='也';
update public.glossary set uz='guruch',                     ru='рис',                  en='rice'                 where zh='米饭';
update public.glossary set uz='lag''mon',                   ru='лапша',                en='noodles'              where zh='面条';
update public.glossary set uz='tayyorlanmoq, tayyorlamoq',  ru='готовить(ся)',         en='to prepare'           where zh='准备';
update public.glossary set uz='hali, yana',                 ru='ещё',                  en='still, more'          where zh='还';
update public.glossary set uz='uzoq (vaqt)',                ru='долго',                en='long (time)'          where zh='久';
update public.glossary set uz='yetib bormoq',               ru='прибыть, добраться',   en='to arrive, to reach'  where zh='到';
update public.glossary set uz='ovqat buyurtma qilmoq',      ru='заказывать еду',       en='to order food'        where zh='点菜';
update public.glossary set uz='ofitsiant',                  ru='официант',             en='waiter, server'       where zh='服务员';
update public.glossary set uz='qo''shimcha ishlamoq',       ru='работать сверхурочно', en='to work overtime'     where zh='加班';
update public.glossary set uz='boshlamoq, boshlanmoq',      ru='начинать(ся)',         en='to begin, to start'   where zh='开始';
update public.glossary set uz='keyin, kelajakda',           ru='потом, в будущем',     en='after, later'         where zh='以后';

-- 再: split the one ambiguous bare character into two unambiguous entries.
-- 再 (kept) now means "then/afterwards" (referenced by hsk2/dialogue5: 以后再买).
update public.glossary set uz='keyin, so''ng', ru='потом, затем', en='then, afterwards' where zh='再';
-- 再来: the restaurant "one more" chunk (referenced by hsk1/dialogue40: 再来一瓶).
insert into public.glossary (zh, py, uz, ru, en, hsk) values
  ('再来', 'zài lái', 'yana (bitta) olib kelmoq', 'заказать/принести ещё', '(to order) one more', 1)
  on conflict (zh, py_norm) do nothing;

-- 借书 (hsk2/dialogue9) vocab.
insert into public.glossary (zh, py, uz, ru, en, hsk) values
  ('图书馆', 'túshūguǎn', 'kutubxona', 'библиотека', 'library', 2),
  ('而且', 'érqiě', 'bundan tashqari', 'к тому же', 'moreover; and also', 2),
  ('当然', 'dāngrán', 'albatta', 'конечно', 'of course', 2),
  ('借', 'jiè', 'olmoq (qarzga); bermoq', 'одолжить; взять', 'to borrow; to lend', 2),
  ('还', 'huán', 'qaytarmoq', 'вернуть', 'to return (something)', 2),
  ('页', 'yè', 'bet (sahifa)', 'страница', 'page', 2)
  on conflict (zh, py_norm) do nothing;

-- 等朋友 (hsk2/dialogue10) vocab + related words.
insert into public.glossary (zh, py, uz, ru, en, hsk) values
  ('谁', 'shéi', 'kim', 'кто', 'who', 1),
  ('发消息', 'fā xiāoxi', 'xabar yubormoq', 'отправить сообщение', 'to send a message', 3),
  ('路上', 'lùshang', 'yo''lda', 'в пути; по дороге', 'on the way', 2),
  ('多久', 'duō jiǔ', 'qancha vaqt', 'как долго', 'how long', 2),
  ('咖啡', 'kāfēi', 'qahva', 'кофе', 'coffee', 1),
  ('堵车', 'dǔchē', 'tirbandlik', 'пробка (на дороге)', 'traffic jam', 3),
  ('大概', 'dàgài', 'taxminan', 'примерно', 'approximately', 3),
  ('点', 'diǎn', 'buyurtma bermoq', 'заказать', 'to order (food/drinks)', 2),
  ('所以', 'suǒyǐ', 'shuning uchun', 'поэтому', 'so; therefore', 2),
  ('消息', 'xiāoxi', 'xabar', 'сообщение; новость', 'message; news', 3),
  ('发', 'fā', 'yubormoq', 'отправлять', 'to send', 2)
  on conflict (zh, py_norm) do nothing;

-- 看病 (hsk2/dialogue11) vocab.
insert into public.glossary (zh, py, uz, ru, en, hsk) values
  ('脸色', 'liǎnsè', 'chehra rangi', 'цвет лица; вид', 'complexion; one''s look', 3),
  ('吃药', 'chī yào', 'dori ichmoq', 'принимать лекарство', 'to take medicine', 2),
  ('陪', 'péi', 'hamrohlik qilmoq', 'сопровождать', 'to accompany', 3),
  ('自己', 'zìjǐ', 'o''zi', 'сам; себя', 'oneself', 2),
  ('度', 'dù', 'gradus', 'градус', 'degree', 2),
  ('高', 'gāo', 'baland', 'высокий', 'high; tall', 1),
  ('马上', 'mǎshàng', 'darhol', 'сразу; немедленно', 'at once; right away', 2),
  ('路口', 'lùkǒu', 'chorraha', 'перекрёсток', 'intersection', 3),
  ('右转', 'yòu zhuǎn', 'o''ngga burilish', 'повернуть направо', 'to turn right', 3)
  on conflict (zh, py_norm) do nothing;

-- 问路 (hsk2/dialogue12) vocab.
insert into public.glossary (zh, py, uz, ru, en, hsk) values
  ('附近', 'fùjìn', 'yaqin atrof', 'окрестности; поблизости', 'nearby; vicinity', 2),
  ('银行', 'yínháng', 'bank', 'банк', 'bank', 2),
  ('一直', 'yìzhí', 'to''g''riga; doimo', 'всё время; прямо', 'straight; continuously', 2),
  ('往前', 'wǎng qián', 'oldinga', 'вперёд', 'forward; ahead', 2),
  ('红绿灯', 'hónglǜdēng', 'svetofor', 'светофор', 'traffic light', 3),
  ('然后', 'ránhòu', 'keyin', 'потом; затем', 'then; afterwards', 2),
  ('米', 'mǐ', 'metr; guruch', 'метр; рис', 'meter; rice', 2),
  ('右边', 'yòubian', 'o''ng tomon', 'справа; правая сторона', 'right side', 2),
  ('公交站', 'gōngjiāo zhàn', 'avtobus bekati', 'автобусная остановка', 'bus stop', 3),
  ('左转', 'zuǒ zhuǎn', 'chapga burilish', 'повернуть налево', 'to turn left', 3)
  on conflict (zh, py_norm) do nothing;
